[build-system]
requires = ["setuptools>=74.1"]
build-backend = "setuptools.build_meta"

[project]
name = "cryostasis"
version = "0.0.1"
dependencies = []

[[tool.setuptools.ext-modules]]
name = "cryostasis._builtin_helpers"
sources = ["src/_builtin_helpers.c"]

#[tool.setuptools]
#packages = ["src/cryostasis"]

#[tool.setuptools.packages.find]
#where = ["src"]
#exclude = ["src/cryostasis/_builtin_helpers.c"]
